# Generated by Django 5.2 on 2025-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0013_merge_20250820_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='https://None.blob.core.windows.net/None/images/default_user.jpg', null=True, upload_to='images'),
        ),
    ]
