# Generated by Django 5.2 on 2025-09-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_auth', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='https://promedhealthplus.blob.core.windows.net/media/images/default_user.jpg', null=True, upload_to='images'),
        ),
    ]
